const STORE = 'rutacontrol-v2';
const previous = JSON.parse(localStorage.getItem('rutacontrol-v1'));
const state = JSON.parse(localStorage.getItem(STORE)) || previous || { vehicles: [], trips: [], maintenance: [] };
state.fuels ||= []; state.expenses ||= [];
state.users ||= [{ id: 'admin-local', name: 'Administrador', username: 'admin', password: 'admin123', role: 'admin', vehicleId: '' }];
const session = JSON.parse(sessionStorage.getItem('rutacontrol-session') || 'null');
let currentUser = session ? state.users.find(user => user.id === session.id && user.role === 'admin') : null;
const mediaDb = new Promise((resolve, reject) => { const request = indexedDB.open('rutacontrol-evidencias', 1); request.onupgradeneeded = () => request.result.createObjectStore('files', { keyPath: 'id' }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
let maintenanceFilter = 'all', editing = null;
const $ = s => document.querySelector(s);
const save = () => localStorage.setItem(STORE, JSON.stringify(state));
const esc = (v = '') => String(v).replace(/[&<>'"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c]));
const dateText = d => d ? new Intl.DateTimeFormat('es-PE',{dateStyle:'medium'}).format(new Date(`${d}T12:00:00`)) : 'Sin fecha';
const collection = type => type === 'maintenance' ? 'maintenance' : `${type}s`;
const vehicle = id => state.vehicles.find(v => v.id === id);
const closed = t => t.endKm !== '' && t.endKm !== undefined && t.endKm !== null;
const distance = t => closed(t) ? Math.max(0, Number(t.endKm) - Number(t.startKm)) : null;
const currentKm = v => Math.max(Number(v.km || 0), ...state.trips.filter(t => t.vehicleId === v.id).map(t => Number(closed(t) ? t.endKm : t.startKm || 0)));
const status = m => { const v = vehicle(m.vehicleId), overKm = Number(m.nextKm || 0) && v && currentKm(v) >= Number(m.nextKm), days = m.nextDate ? Math.ceil((new Date(`${m.nextDate}T12:00:00`) - new Date()) / 86400000) : 999; return overKm || days < 0 ? 'danger' : (days <= 30 || (Number(m.nextKm || 0) && v && Number(m.nextKm) - currentKm(v) <= 500)) ? 'warn' : 'ok'; };
const statusLabel = s => s === 'danger' ? 'Vencido' : s === 'warn' ? 'Próximo' : 'Programado';
async function saveEvidence(tripId, stage, files) { if (!files?.length) return; const db = await mediaDb, tx = db.transaction('files', 'readwrite'), store = tx.objectStore('files'); [...files].forEach(file => store.put({ id: `${tripId}:${stage}:${crypto.randomUUID()}`, tripId, stage, name: file.name, type: file.type, file })); await new Promise((resolve, reject) => { tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }); }
async function evidenceFor(tripId, stage) { const db = await mediaDb, tx = db.transaction('files', 'readonly'), request = tx.objectStore('files').getAll(); return new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result.filter(item => item.tripId === tripId && item.stage === stage)); request.onerror = () => reject(request.error); }); }
async function removeEvidence(tripId) { const db = await mediaDb, tx = db.transaction('files', 'readwrite'), store = tx.objectStore('files'), request = store.getAll(); request.onsuccess = () => request.result.filter(item => item.tripId === tripId).forEach(item => store.delete(item.id)); }
async function renderEvidence(recordId) { for (const stage of ['outbound', 'return', 'fuel', 'expense', 'plate', 'start-km', 'end-km']) { const target = $(`#evidence-${stage}`); if (!target) continue; const files = await evidenceFor(recordId, stage); target.innerHTML = files.length ? files.map(item => item.type.startsWith('video/') ? `<video controls src="${URL.createObjectURL(item.file)}"></video>` : `<img src="${URL.createObjectURL(item.file)}" alt="Evidencia ${stage}">`).join('') : '<small>Aún no hay evidencias guardadas.</small>'; } }

function render() { renderDashboard(); renderTrips(); renderMaintenance(); renderVehicles(); renderFuels(); renderExpenses(); renderDrivers(); }
function renderDashboard() {
  const km = state.trips.reduce((n,t) => n + (distance(t) || 0), 0), open = state.trips.filter(t => !closed(t)).length, alerts = state.maintenance.filter(m => status(m) !== 'ok').length;
  $('#metrics').innerHTML = `<div class="metric"><span class="metric-label">Vehículos registrados</span><div class="metric-value">${state.vehicles.length}</div><small>En tu flota</small></div><div class="metric"><span class="metric-label">Kilómetros recorridos</span><div class="metric-value">${km.toLocaleString('es-PE')}</div><small>Recorridos finalizados</small></div><div class="metric"><span class="metric-label">Vehículos en ruta</span><div class="metric-value">${open}</div><small>Con retorno pendiente</small></div><div class="metric"><span class="metric-label">Alertas de mantenimiento</span><div class="metric-value">${alerts}</div><small>Por revisar o vencidas</small></div>`;
  const trips = [...state.trips].sort((a,b) => (b.departureDate || b.date || '').localeCompare(a.departureDate || a.date || '')).slice(0,4);
  $('#recent-trips').innerHTML = trips.length ? trips.map(t => { const v = vehicle(t.vehicleId) || {}, d = distance(t), tripDate = t.departureDate || t.date, route = t.origin && t.destination ? `${t.origin} → ${t.destination}` : t.route; return `<div class="compact-row"><div class="icon">↗</div><div class="row-main"><b>${esc(v.plate || 'Vehículo eliminado')} · ${esc(t.driver)}</b><span>${dateText(tripDate)}${t.departureTime ? ` · ${esc(t.departureTime)}` : ''} · ${esc(route)}</span></div>${d === null ? '<span class="badge warn">En ruta</span>' : `<b>${d.toLocaleString('es-PE')} km</b>`}</div>`; }).join('') : '<div class="empty">Registra una salida para verla aquí.</div>';
  const items = state.maintenance.filter(m => status(m) !== 'ok').slice(0,4);
  $('#upcoming-maintenance').innerHTML = items.length ? items.map(m => { const v = vehicle(m.vehicleId) || {}, s = status(m); return `<div class="compact-row"><div class="icon">♧</div><div class="row-main"><b>${esc(m.type)} · ${esc(v.plate || 'Sin vehículo')}</b><span>Próximo: ${m.nextDate ? dateText(m.nextDate) : `${Number(m.nextKm || 0).toLocaleString('es-PE')} km`}</span></div><span class="badge ${s}">${statusLabel(s)}</span></div>`; }).join('') : '<div class="empty">No hay alertas pendientes.</div>';
}
function renderTrips() {
  const trips = [...state.trips].filter(t => !currentUser || currentUser.role === 'admin' || t.driver === currentUser.name).sort((a,b) => (b.departureDate || b.date || '').localeCompare(a.departureDate || a.date || ''));
  $('#trips-body').innerHTML = trips.map(t => { const v = vehicle(t.vehicleId) || {}, d = distance(t), km = d === null ? `${Number(t.startKm).toLocaleString('es-PE')} → Pendiente` : `${Number(t.startKm).toLocaleString('es-PE')} → ${Number(t.endKm).toLocaleString('es-PE')}`, tripDate = t.departureDate || t.date, route = t.origin && t.destination ? `${t.origin} → ${t.destination}` : t.route; return `<tr><td>${dateText(tripDate)}${t.departureTime ? `<br><span>${esc(t.departureTime)}</span>` : ''}</td><td class="cell-main"><b>${esc(v.plate || 'Eliminado')}</b><span>${esc(v.brand || '')}</span></td><td>${esc(t.driver)}</td><td>${esc(route)}</td><td>${km}</td><td>${d === null ? '<span class="badge warn">En ruta</span>' : `<b>${d.toLocaleString('es-PE')} km</b>`}</td><td><button class="edit" data-edit="trip" data-id="${t.id}">Editar</button><button class="delete" data-delete="trip" data-id="${t.id}">×</button></td></tr>`; }).join('');
  $('#trips-empty').style.display = trips.length ? 'none' : 'block';
}
function renderMaintenance() {
  let items = [...state.maintenance].sort((a,b) => (a.nextDate || '9999').localeCompare(b.nextDate || '9999')); if (maintenanceFilter === 'urgent') items = items.filter(m => status(m) !== 'ok');
  $('#maintenance-list').innerHTML = items.map(m => { const v = vehicle(m.vehicleId) || {}, s = status(m), now = v.id ? currentKm(v) : 0, total = Math.max(1, Number(m.nextKm) - Number(m.serviceKm || 0)), pct = Math.min(100,Math.max(0,(now-Number(m.serviceKm || 0))*100/total)); return `<article class="maintenance-card"><div class="card-top"><div><h3>${esc(m.type)}</h3><p>${esc(v.plate || 'Vehículo eliminado')} · ${esc(v.brand || '')}</p></div><span class="badge ${s}">${statusLabel(s)}</span></div><div class="info-line">Realizado: ${dateText(m.date)}${m.serviceKm ? ` · ${Number(m.serviceKm).toLocaleString('es-PE')} km` : ''}</div><div class="progress ${s === 'ok' ? '' : 'warning'}"><i style="width:${pct}%"></i></div><div class="info-line">Próximo: ${m.nextDate ? dateText(m.nextDate) : '—'}${m.nextKm ? ` o ${Number(m.nextKm).toLocaleString('es-PE')} km` : ''}</div><div class="card-foot"><span>${esc(m.notes || 'Sin observaciones')}</span><span><button class="edit" data-edit="maintenance" data-id="${m.id}">Editar</button><button class="delete" data-delete="maintenance" data-id="${m.id}">Eliminar</button></span></div></article>`; }).join('');
  $('#maintenance-empty').style.display = items.length ? 'none' : 'block';
}
function renderVehicles() { $('#vehicles-list').innerHTML = state.vehicles.map(v => `<article class="vehicle-card"><div class="card-top"><span class="badge ${v.status === 'En mantenimiento' ? 'warn' : v.status === 'Fuera de servicio' ? 'danger' : 'ok'}">${esc(v.status || 'Disponible')}</span><span><button class="edit" data-edit="vehicle" data-id="${v.id}">Editar</button><button class="delete" data-delete="vehicle" data-id="${v.id}">×</button></span></div><div class="vehicle-plate">${esc(v.plate)}</div><p>${esc(v.brand)} ${esc(v.model || '')}</p><div class="info-line">Odómetro actual</div><h2>${currentKm(v).toLocaleString('es-PE')} km</h2><div class="card-foot"><span>${esc(v.year || '—')}</span><span>${esc(v.color || 'Sin color')}</span></div></article>`).join(''); $('#vehicles-empty').style.display = state.vehicles.length ? 'none' : 'block'; }
function renderFuels() { const list=[...state.fuels].sort((a,b)=>(b.date||'').localeCompare(a.date||'')); $('#fuel-body').innerHTML=list.map(f=>{const v=vehicle(f.vehicleId)||{};return `<tr><td>${dateText(f.date)}</td><td>${esc(v.plate||'Eliminado')}</td><td>${esc(f.provider||'—')}</td><td>${Number(f.liters||0).toLocaleString('es-PE')}</td><td>S/ ${Number(f.cost||0).toFixed(2)}</td><td>${Number(f.km||0).toLocaleString('es-PE')} km</td><td><button class="edit" data-edit="fuel" data-id="${f.id}">Editar</button><button class="delete" data-delete="fuel" data-id="${f.id}">×</button></td></tr>`}).join('');$('#fuel-empty').style.display=list.length?'none':'block'; }
function renderExpenses() { const list=[...state.expenses].sort((a,b)=>(b.date||'').localeCompare(a.date||'')); $('#expenses-body').innerHTML=list.map(x=>{const v=vehicle(x.vehicleId)||{};return `<tr><td>${dateText(x.date)}</td><td>${esc(v.plate||'Eliminado')}</td><td>${esc(x.type)}</td><td>${esc(x.detail)}</td><td>${esc(x.provider||'—')}</td><td>S/ ${Number(x.cost||0).toFixed(2)}</td><td><button class="edit" data-edit="expense" data-id="${x.id}">Editar</button><button class="delete" data-delete="expense" data-id="${x.id}">×</button></td></tr>`}).join('');$('#expenses-empty').style.display=list.length?'none':'block'; }
function renderDrivers() { if (!$('#drivers-list')) return; const select=$('#driver-vehicle'); select.innerHTML=`<option value="">Sin asignar</option>${state.vehicles.map(v=>`<option value="${v.id}">${esc(v.plate)} · ${esc(v.brand)}</option>`).join('')}`; const drivers=state.users.filter(user=>user.role==='driver'); $('#drivers-list').innerHTML=drivers.length?drivers.map(user=>`<div class="compact-row"><div class="icon">♙</div><div class="row-main"><b>${esc(user.name)}</b><span>@${esc(user.username)} · ${esc(vehicle(user.vehicleId)?.plate || 'Sin vehículo asignado')}</span></div><button class="delete" data-delete-user="${user.id}">×</button></div>`).join(''):'<div class="empty">Aún no hay choferes registrados.</div>'; }

const fields = { vehicle:[['plate','Placa','text',true],['brand','Marca','text',true],['model','Modelo','text'],['year','Año','number'],['km','Kilometraje inicial / actual','number',true],['status','Estado del vehículo','selectStatus',true],['color','Color','text']], trip:[['plateScan','1. Foto de la placa (registra fecha y hora)','scan'],['vehicleId','Vehículo','select',true],['departureDate','Fecha de salida','date',true],['departureTime','Hora de salida','time',true],['driver','Responsable / conductor','text',true],['origin','Origen','text',true],['destination','Destino final','text',true],['startScan','2. Foto del odómetro de salida','scan'],['startKm','Kilometraje de salida','number',true],['endScan','3. Foto del odómetro de retorno','scan'],['endKm','Kilometraje de retorno (al regresar)','number'],['outboundMedia','Otras evidencias de salida (fotos o videos)','media'],['returnMedia','Otras evidencias de retorno (fotos o videos)','media'],['notes','Observaciones','textarea']], maintenance:[['vehicleId','Vehículo','select',true],['type','Tipo de mantenimiento','selectType',true],['date','Fecha del servicio','date',true],['serviceKm','Kilometraje del servicio','number'],['nextDate','Próxima fecha programada','date'],['nextKm','Próximo kilometraje programado','number'],['notes','Detalle / observaciones','textarea']], fuel:[['vehicleId','Vehículo','select',true],['date','Fecha de abastecimiento','date',true],['provider','Grifo / proveedor','text',true],['liters','Cantidad de litros','number',true],['cost','Costo total (S/)','number',true],['km','Kilometraje al abastecer','number',true],['fuelMedia','Foto del comprobante','media']], expense:[['vehicleId','Vehículo','select',true],['date','Fecha','date',true],['type','Tipo de gasto','selectExpense',true],['detail','Detalle del gasto o reparación','text',true],['provider','Taller / proveedor','text'],['cost','Costo total (S/)','number',true],['expenseMedia','Foto del comprobante','media']] };
function control(name, kind, required, value = '') { const req = required ? 'required' : '', val = esc(value); if (kind === 'textarea') return `<textarea id="f-${name}" name="${name}">${val}</textarea>`; if (kind === 'scan') { const stage=({plateScan:'plate',startScan:'start-km',endScan:'end-km'})[name]; return `<input id="f-${name}" type="file" accept="image/*" capture="environment"><small id="scan-status-${name}">Usa la cámara o selecciona una foto.</small><div class="evidence-preview" id="evidence-${stage}"></div>`; } if (kind === 'media') { const stage = ({outboundMedia:'outbound',returnMedia:'return',fuelMedia:'fuel',expenseMedia:'expense'})[name]; return `<input id="f-${name}" name="${name}" type="file" accept="image/*,video/*" multiple><small>Selecciona fotos o videos. Para videos, usa archivos cortos.</small><div class="evidence-preview" id="evidence-${stage}"></div>`; } if (kind === 'select') { const allowed=currentUser?.role==='driver'&&currentUser.vehicleId?state.vehicles.filter(v=>v.id===currentUser.vehicleId):state.vehicles; return `<select id="f-${name}" name="${name}" ${req}>${allowed.map(v => `<option value="${v.id}" ${v.id === value ? 'selected' : ''}>${esc(v.plate)} · ${esc(v.brand)}</option>`).join('')}</select>`; } if (kind === 'selectStatus') { const options=['Disponible','En ruta','En mantenimiento','Fuera de servicio']; return `<select id="f-${name}" name="${name}" ${req}>${options.map(x=>`<option ${x===(value||'Disponible')?'selected':''}>${x}</option>`).join('')}</select>`; } if (kind === 'selectExpense') { const options=['Parche de llanta','Cambio de neumático','Reparación mecánica','Repuesto','Mano de obra','Lavado','Peaje','Otro']; return `<select id="f-${name}" name="${name}" ${req}>${options.map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}</select>`; } if (kind === 'selectType') { const types=['Afinamiento general','Cambio de aceite y filtros','Revisión de frenos','Rotación / cambio de neumáticos','Revisión técnica','Reparación correctiva','Otro']; return `<select id="f-${name}" name="${name}" ${req}>${types.map(t => `<option ${t === value ? 'selected' : ''}>${t}</option>`).join('')}</select>`; } return `<input id="f-${name}" name="${name}" type="${kind}" value="${val}" ${req} ${kind === 'number' ? 'min="0" step="0.01"' : ''}>`; }
function openForm(type, record = null) { if (type !== 'vehicle' && !state.vehicles.length) { alert('Primero registra al menos un vehículo.'); setView('vehicles'); return; } editing = record ? {type,id:record.id} : null; const labels={trip:'recorrido',vehicle:'vehículo',maintenance:'mantenimiento',fuel:'combustible',expense:'gasto'}; $('#form-title').textContent = record ? `Editar ${labels[type]}` : type === 'trip' ? 'Registrar salida de vehículo' : type === 'vehicle' ? 'Agregar vehículo' : type === 'maintenance' ? 'Registrar mantenimiento' : type === 'fuel' ? 'Registrar combustible' : 'Registrar gasto o reparación'; $('#record-form').dataset.type=type; $('#form-fields').innerHTML=fields[type].map(([n,l,k,r])=>`<div class="field ${k==='textarea'||k==='media'||k==='scan'?'full':''}"><label for="f-${n}">${l}${r?' *':''}</label>${control(n,k,r,record?.[n] ?? '')}</div>`).join(''); if (record && type === 'trip' && !record.departureDate) { $('#f-departureDate').value=record.date || ''; $('#f-origin').value=record.route || ''; } if (!record && type === 'trip') { $('#f-departureDate').value=new Date().toISOString().slice(0,10); $('#f-departureTime').value=new Date().toTimeString().slice(0,5); $('#f-driver').value=currentUser?.role==='driver'?currentUser.name:''; if(currentUser?.role==='driver') $('#f-driver').readOnly=true; const v=vehicle($('#f-vehicleId').value); if(v) $('#f-startKm').value=currentKm(v); } if (!record && ['maintenance','fuel'].includes(type)) { $('#f-date').value=new Date().toISOString().slice(0,10); const v=vehicle($('#f-vehicleId').value); if(v && type==='maintenance') $('#f-serviceKm').value=currentKm(v); if(v && type==='fuel') $('#f-km').value=currentKm(v); } if (!record && type==='expense') $('#f-date').value=new Date().toISOString().slice(0,10); $('#form-dialog').showModal(); if(record && ['trip','fuel','expense'].includes(type)) renderEvidence(record.id); }
async function scanPhoto(kind, file) { const message=$(`#scan-status-${kind}`); if (!file) return; if (kind==='plateScan') { const now=new Date(); $('#f-departureDate').value=now.toISOString().slice(0,10); $('#f-departureTime').value=now.toTimeString().slice(0,5); }
  if (!('TextDetector' in window)) { message.textContent='Foto tomada. Tu navegador no puede leer texto automáticamente; verifica o completa el dato manualmente.'; return; }
  try { const bitmap=await createImageBitmap(file), detector=new TextDetector(), result=await detector.detect(bitmap); bitmap.close(); const text=result.map(item=>item.rawValue).join(' ').toUpperCase();
    if (kind==='plateScan') { const normalized=text.replace(/[^A-Z0-9]/g,''); const match=state.vehicles.find(item=>normalized.includes(String(item.plate).replace(/[^A-Z0-9]/gi,'').toUpperCase())); if(match){$('#f-vehicleId').value=match.id;message.textContent=`Placa reconocida: ${match.plate}. Fecha y hora registradas.`;}else message.textContent='Foto tomada y fecha/hora registradas. No se pudo identificar la placa; selecciónala manualmente.'; }
    else { const candidates=(text.match(/\d[\d\s,.]{2,}/g)||[]).map(item=>Number(item.replace(/[^0-9]/g,''))).filter(value=>value>0); const value=candidates.sort((a,b)=>b-a)[0]; const target=kind==='startScan'?'#f-startKm':'#f-endKm'; if(value){$(target).value=value;message.textContent=`Kilometraje leído: ${value.toLocaleString('es-PE')} km. Verifícalo antes de guardar.`;}else message.textContent='No se pudo leer el kilometraje. Escríbelo manualmente.'; }
  } catch { message.textContent='No se pudo leer la foto. Escribe el dato manualmente.'; }
}
document.addEventListener('change',event=>{ const input=event.target; if(['f-plateScan','f-startScan','f-endScan'].includes(input.id)) scanPhoto(input.id.replace('f-',''),input.files?.[0]); });
function setView(view) { if(view==='users'&&currentUser?.role!=='admin') view='dashboard'; document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view)); document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===view)); $('#page-title').textContent={dashboard:'Resumen general',trips:'Control de recorridos',maintenance:'Mantenimiento y afinamiento',vehicles:'Vehículos',fuel:'Control de combustible',expenses:'Gastos y reparaciones',reports:'Reportes',users:'Choferes y accesos'}[view]; $('#main-action').style.display=view==='dashboard'?'block':'none'; render(); }
document.addEventListener('click',e=>{ const nav=e.target.closest('.nav-link'); if(nav)setView(nav.dataset.view); const go=e.target.closest('[data-go]');if(go)setView(go.dataset.go);const edit=e.target.closest('[data-edit]');if(edit){const type=edit.dataset.edit;openForm(type,state[collection(type)].find(x=>x.id===edit.dataset.id));}const del=e.target.closest('[data-delete]');if(del&&confirm('¿Eliminar este registro?')){const c=collection(del.dataset.delete); if(['trip','fuel','expense'].includes(del.dataset.delete)) removeEvidence(del.dataset.id); state[c]=state[c].filter(x=>x.id!==del.dataset.id);save();render();}const deleteUser=e.target.closest('[data-delete-user]');if(deleteUser&&confirm('¿Eliminar esta cuenta de chofer?')){state.users=state.users.filter(user=>user.id!==deleteUser.dataset.deleteUser);save();render();} });
$('#main-action').onclick=()=>openForm('trip'); $('#add-trip').onclick=()=>openForm('trip'); $('#add-maintenance').onclick=()=>openForm('maintenance'); $('#add-vehicle').onclick=()=>openForm('vehicle'); $('#add-fuel').onclick=()=>openForm('fuel'); $('#add-expense').onclick=()=>openForm('expense'); document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{maintenanceFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderMaintenance();});
$('#record-form').addEventListener('submit',async e=>{const type=e.currentTarget.dataset.type;if(e.submitter?.value==='cancel')return;e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget)), outbound=$('#f-outboundMedia')?.files, returning=$('#f-returnMedia')?.files, fuelMedia=$('#f-fuelMedia')?.files, expenseMedia=$('#f-expenseMedia')?.files, plate=$('#f-plateScan')?.files, startScan=$('#f-startScan')?.files, endScan=$('#f-endScan')?.files;delete data.outboundMedia;delete data.returnMedia;delete data.fuelMedia;delete data.expenseMedia;if(type==='trip'&&data.endKm&&Number(data.endKm)<Number(data.startKm)){alert('El kilometraje de retorno no puede ser menor al de salida.');return;}const c=collection(type);let id;if(editing){const i=state[c].findIndex(x=>x.id===editing.id);state[c][i]={...state[c][i],...data};id=editing.id;}else{id=crypto.randomUUID();state[c].push({...data,id});}try{if(type==='trip'){await saveEvidence(id,'plate',plate);await saveEvidence(id,'start-km',startScan);await saveEvidence(id,'end-km',endScan);await saveEvidence(id,'outbound',outbound);await saveEvidence(id,'return',returning);}if(type==='fuel')await saveEvidence(id,'fuel',fuelMedia);if(type==='expense')await saveEvidence(id,'expense',expenseMedia);}catch(error){alert('El registro se guardó, pero no fue posible guardar algún archivo. Prueba con un video más pequeño.');}save();render();$('#form-dialog').close();});
function csvValue(value) { return `"${String(value ?? '').replaceAll('"','""')}"`; }
function exportExcel() { const rows=[['Tipo','Fecha','Vehículo','Detalle','Costo (S/)','Kilometraje'], ...state.trips.map(t=>['Recorrido',t.departureDate||t.date,vehicle(t.vehicleId)?.plate,`${t.origin||''} → ${t.destination||t.route||''}`,distance(t) ?? '',t.endKm||t.startKm]), ...state.fuels.map(f=>['Combustible',f.date,vehicle(f.vehicleId)?.plate,`${f.liters} litros · ${f.provider||''}`,f.cost,f.km]), ...state.expenses.map(x=>['Gasto / reparación',x.date,vehicle(x.vehicleId)?.plate,`${x.type}: ${x.detail}`,x.cost,''])]; const blob=new Blob(['\ufeff'+rows.map(row=>row.map(csvValue).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}), link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`RutaControl_${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href); }
function exportPdf() { const summary=`<h1>FRUTOS TROPICALES EXPORT. PERÚ</h1><h2>Reporte de control vehicular</h2><p>Generado: ${new Date().toLocaleString('es-PE')}</p><h3>Resumen</h3><ul><li>Vehículos: ${state.vehicles.length}</li><li>Recorridos: ${state.trips.length}</li><li>Combustible: S/ ${state.fuels.reduce((n,x)=>n+Number(x.cost||0),0).toFixed(2)}</li><li>Gastos y reparaciones: S/ ${state.expenses.reduce((n,x)=>n+Number(x.cost||0),0).toFixed(2)}</li></ul><h3>Gastos y reparaciones</h3><table><tr><th>Fecha</th><th>Vehículo</th><th>Detalle</th><th>Costo</th></tr>${state.expenses.map(x=>`<tr><td>${dateText(x.date)}</td><td>${esc(vehicle(x.vehicleId)?.plate||'')}</td><td>${esc(x.type)} · ${esc(x.detail)}</td><td>S/ ${Number(x.cost||0).toFixed(2)}</td></tr>`).join('')}</table><style>body{font-family:Arial;padding:28px;color:#20342c}h1{color:#187b52}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}</style>`;const report=window.open('','_blank');report.document.write(summary);report.document.close();report.focus();report.print(); }
$('#export-excel').onclick=exportExcel; $('#export-pdf').onclick=exportPdf;
$('#driver-form').addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));if(state.users.some(user=>user.username.toLowerCase()===data.username.trim().toLowerCase())){alert('Ese usuario ya existe.');return;}state.users.push({id:crypto.randomUUID(),name:data.name.trim(),username:data.username.trim(),password:data.password,vehicleId:data.vehicleId,role:'driver'});save();event.currentTarget.reset();renderDrivers();alert('Cuenta de chofer creada correctamente.');});
function activateSession() { $('#login-screen').classList.add('hidden'); $('#session-name').textContent=`${currentUser.name} · ${currentUser.role==='admin'?'Administrador':'Chofer'}`; document.querySelectorAll('.admin-only').forEach(item=>item.style.display=currentUser.role==='admin'?'flex':'none'); render(); }
$('#login-form').addEventListener('submit',event=>{event.preventDefault();const username=$('#login-user').value.trim().toLowerCase(), password=$('#login-password').value;const user=state.users.find(item=>item.role==='admin'&&item.username.toLowerCase()===username&&item.password===password);if(!user){$('#login-error').textContent='Acceso permitido solo para administrador.';return;}currentUser=user;sessionStorage.setItem('rutacontrol-session',JSON.stringify({id:user.id}));$('#login-error').textContent='';activateSession();});
$('#logout').onclick=()=>{sessionStorage.removeItem('rutacontrol-session');currentUser=null;$('#login-form').reset();$('#login-screen').classList.remove('hidden');};
if(currentUser) activateSession();
